version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hospitality
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  hospitality-client:
    image: hospitality/client
    container_name: hospitality-client
    build: ./client
    ports:
      - "4200:4200"
    volumes:
      - ./client:/opt/project

volumes:
  postgres_data:
    driver: local
